version: '3.8'

networks:
  vk-api:

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: Databaza
    environment:
      MYSQL_ROOT_PASSWORD: heslo
      MYSQL_DATABASE: databaza
      MYSQL_USER: pouzivatel
      MYSQL_PASSWORD: heslo
    ports:
      - "3306:3306"
    networks:
      - vk-api
    volumes:
      - vk-dbdata:/var/lib/mysql

  vk-web:
    image: library/nginx:1.20.1
    container_name: VkWeb
    ports:
      - "8086:80"
    networks:
      - vk-api
    depends_on:
      - vk-php
    volumes:
      - ./src:/var/www/html
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf

  vk-php:
    build:
      context: .
      dockerfile: config/docker/Dockerfile
    image: ppsdocker/vk-php
    container_name: VkPhp
    expose:
      - 9000
    networks:
      - vk-api
    depends_on:
      - db
    volumes:
      - ./src:/var/www/html


volumes:
  vk-dbdata: