version: '3.8'

networks:
  vk:

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-apache
    image: vk-apache-2
    container_name: Web
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    networks:
      - vk
    depends_on:
      - db

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: Databaza
    environment:
      MYSQL_ROOT_PASSWORD: heslo
      MYSQL_DATABASE: databaza
      MYSQL_USER: pouzivatel
      MYSQL_PASSWORD: heslo
    ports:
      - "3306:3306"
    networks:
      - vk
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: